### PR TITLE
feat: Add classes to image emojis

### PR DESCRIPTION
**Pull request by HowToCodeDE**
Add classes to image emojis, to style them with CSS, as requested in #112

### CODE REVIEW

**Comment by UziTech** [comment]
I'm ok with adding `marked-emoji` class but adding the emoji name could be a problem since the name could be any string and it can cause problems if emoji name had a quote or something like that.

**Comment by baseplate-admin** [comment]
Hi, can we get this moving? 


@HowToCodeDE do you need any help with anything? ``

**Comment by baseplate-admin** [comment]
I unfortunately need this in my application. I hope you dont mind if i work where you left off @HowToCodeDE

**Comment by UziTech** [comment]
I'm going to close this since there is a work around in #112

**Pull request closed without merging**
