### PR TITLE
feat: add name option to prevent collision from multiple instances

### PR DESCRIPTION
**Pull request by Tigriz**
Ref: #88

### CODE REVIEW

**Comment by UziTech** [comment]
I think a better solution might be to allow the emoji object to include an object with a property to tell if it is a url or unicode.

Something like:

```js
{ 
  confetti: {
    url:  'https://github.githubassets.com/images/icons/emoji/unicode/1f389.png?v8'
  },
  heart: {
    char: '❤️'
  }
}
```

**Comment by Tigriz** [comment]
By removing `unicode: boolean` option?
If we keep it, then what `unicode` value would be for mixed char/url?
`unicode: undefined` = mixed ? And which default option value for `unicode` ?

**Comment by UziTech** [comment]
The `unicode` option could still be used if the emojis object values are strings. If the emojis object values are objects than try to get `char` otherwise fallback to `url`.

**Comment by UziTech** [comment]
I created #99 to fix this. Check if it solves your problem before I merge it.

**Comment by Tigriz** [comment]
@UziTech indeed, it perfectly fills my needs, ty

**Pull request closed without merging**
